// const.ts
export const actionTypes = {
  SET_COURSE_ID: "SET_COURSE_ID",
  SET_PROGRESS: "SET_PROGRESS",
  SET_CURRENT_UNIT: "SET_CURRENT_UNIT",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_ALL_UNITS: "SET_ALL_UNITS",
  SET_COURSE_INFO: "SET_COURSE_INFO",
  FETCH_COURSE_DATA: "FETCH_COURSE_DATA",
  NEXT_UNIT: "NEXT_UNIT",
  PREV_UNIT: "PREV_UNIT",
  SET_USER_INFO: "SET_USER_INFO",
};
