export const actionTypes = {
  SET_COURSE_ID: "SET_COURSE_ID",
  SET_PROGRESS: "SET_PROGRESS",
  SET_CURRENT_UNIT: "SET_CURRENT_UNIT",
  SET_TOKEN: "SET_TOKEN",
  SET_IS_LOADING: "SET_IS_LOADING",
  SET_ERROR: "SET_ERROR",
  SET_ALL_UNITS: "SET_ALL_UNITS",
  SET_COURSE_INFO: "SET_COURSE_INFO",
};
